version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: github-actions
    target-branch: develop
    directory: /
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: weekly

  # Enable version updates for npm
  - package-ecosystem: npm
    target-branch: develop
    # Look for a `package.json` in the `root` directory
    directory: /
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: weekly
