/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as PublicImport } from './routes/_public'
import { Route as MarketingImport } from './routes/_marketing'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as MarketingIndexImport } from './routes/_marketing.index'
import { Route as AuthAuthVerifyImport } from './routes/auth/auth-verify'
import { Route as AuthAuthErrorImport } from './routes/auth/auth-error'
import { Route as AuthAuthConfirmImport } from './routes/auth/auth-confirm'
import { Route as MarketingContactImport } from './routes/_marketing.contact'
import { Route as PublicProfileSlugIndexImport } from './routes/_public/$profileSlug/index'
import { Route as AuthedDashboardIndexImport } from './routes/_authed/dashboard/index'
import { Route as PublicProfileSlugListSlugImport } from './routes/_public/$profileSlug/$listSlug'
import { Route as AuthedDashboardAccountRouteImport } from './routes/_authed/dashboard/account/route'
import { Route as AuthedDashboardProfileSlugRouteImport } from './routes/_authed/dashboard/$profileSlug/route'
import { Route as AuthedDashboardAccountIndexImport } from './routes/_authed/dashboard/account/index'
import { Route as AuthedDashboardProfileSlugIndexImport } from './routes/_authed/dashboard/$profileSlug/index'
import { Route as AuthedDashboardProfileSlugListSlugImport } from './routes/_authed/dashboard/$profileSlug/$listSlug'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const MarketingRoute = MarketingImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const MarketingIndexRoute = MarketingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)

const AuthAuthVerifyRoute = AuthAuthVerifyImport.update({
  id: '/auth-verify',
  path: '/auth-verify',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthAuthErrorRoute = AuthAuthErrorImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthAuthConfirmRoute = AuthAuthConfirmImport.update({
  id: '/auth-confirm',
  path: '/auth-confirm',
  getParentRoute: () => AuthRouteRoute,
} as any)

const MarketingContactRoute = MarketingContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)

const PublicProfileSlugIndexRoute = PublicProfileSlugIndexImport.update({
  id: '/$profileSlug/',
  path: '/$profileSlug/',
  getParentRoute: () => PublicRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)

const PublicProfileSlugListSlugRoute = PublicProfileSlugListSlugImport.update({
  id: '/$profileSlug/$listSlug',
  path: '/$profileSlug/$listSlug',
  getParentRoute: () => PublicRoute,
} as any)

const AuthedDashboardAccountRouteRoute =
  AuthedDashboardAccountRouteImport.update({
    id: '/dashboard/account',
    path: '/dashboard/account',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedDashboardProfileSlugRouteRoute =
  AuthedDashboardProfileSlugRouteImport.update({
    id: '/dashboard/$profileSlug',
    path: '/dashboard/$profileSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedDashboardAccountIndexRoute =
  AuthedDashboardAccountIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardAccountRouteRoute,
  } as any)

const AuthedDashboardProfileSlugIndexRoute =
  AuthedDashboardProfileSlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardProfileSlugRouteRoute,
  } as any)

const AuthedDashboardProfileSlugListSlugRoute =
  AuthedDashboardProfileSlugListSlugImport.update({
    id: '/$listSlug',
    path: '/$listSlug',
    getParentRoute: () => AuthedDashboardProfileSlugRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactImport
      parentRoute: typeof MarketingImport
    }
    '/auth/auth-confirm': {
      id: '/auth/auth-confirm'
      path: '/auth-confirm'
      fullPath: '/auth/auth-confirm'
      preLoaderRoute: typeof AuthAuthConfirmImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/auth-error': {
      id: '/auth/auth-error'
      path: '/auth-error'
      fullPath: '/auth/auth-error'
      preLoaderRoute: typeof AuthAuthErrorImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/auth-verify': {
      id: '/auth/auth-verify'
      path: '/auth-verify'
      fullPath: '/auth/auth-verify'
      preLoaderRoute: typeof AuthAuthVerifyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexImport
      parentRoute: typeof MarketingImport
    }
    '/_authed/dashboard/$profileSlug': {
      id: '/_authed/dashboard/$profileSlug'
      path: '/dashboard/$profileSlug'
      fullPath: '/dashboard/$profileSlug'
      preLoaderRoute: typeof AuthedDashboardProfileSlugRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/dashboard/account': {
      id: '/_authed/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof AuthedDashboardAccountRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_public/$profileSlug/$listSlug': {
      id: '/_public/$profileSlug/$listSlug'
      path: '/$profileSlug/$listSlug'
      fullPath: '/$profileSlug/$listSlug'
      preLoaderRoute: typeof PublicProfileSlugListSlugImport
      parentRoute: typeof PublicImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_public/$profileSlug/': {
      id: '/_public/$profileSlug/'
      path: '/$profileSlug'
      fullPath: '/$profileSlug'
      preLoaderRoute: typeof PublicProfileSlugIndexImport
      parentRoute: typeof PublicImport
    }
    '/_authed/dashboard/$profileSlug/$listSlug': {
      id: '/_authed/dashboard/$profileSlug/$listSlug'
      path: '/$listSlug'
      fullPath: '/dashboard/$profileSlug/$listSlug'
      preLoaderRoute: typeof AuthedDashboardProfileSlugListSlugImport
      parentRoute: typeof AuthedDashboardProfileSlugRouteImport
    }
    '/_authed/dashboard/$profileSlug/': {
      id: '/_authed/dashboard/$profileSlug/'
      path: '/'
      fullPath: '/dashboard/$profileSlug/'
      preLoaderRoute: typeof AuthedDashboardProfileSlugIndexImport
      parentRoute: typeof AuthedDashboardProfileSlugRouteImport
    }
    '/_authed/dashboard/account/': {
      id: '/_authed/dashboard/account/'
      path: '/'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof AuthedDashboardAccountIndexImport
      parentRoute: typeof AuthedDashboardAccountRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthAuthConfirmRoute: typeof AuthAuthConfirmRoute
  AuthAuthErrorRoute: typeof AuthAuthErrorRoute
  AuthAuthVerifyRoute: typeof AuthAuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthConfirmRoute: AuthAuthConfirmRoute,
  AuthAuthErrorRoute: AuthAuthErrorRoute,
  AuthAuthVerifyRoute: AuthAuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedDashboardProfileSlugRouteRouteChildren {
  AuthedDashboardProfileSlugListSlugRoute: typeof AuthedDashboardProfileSlugListSlugRoute
  AuthedDashboardProfileSlugIndexRoute: typeof AuthedDashboardProfileSlugIndexRoute
}

const AuthedDashboardProfileSlugRouteRouteChildren: AuthedDashboardProfileSlugRouteRouteChildren =
  {
    AuthedDashboardProfileSlugListSlugRoute:
      AuthedDashboardProfileSlugListSlugRoute,
    AuthedDashboardProfileSlugIndexRoute: AuthedDashboardProfileSlugIndexRoute,
  }

const AuthedDashboardProfileSlugRouteRouteWithChildren =
  AuthedDashboardProfileSlugRouteRoute._addFileChildren(
    AuthedDashboardProfileSlugRouteRouteChildren,
  )

interface AuthedDashboardAccountRouteRouteChildren {
  AuthedDashboardAccountIndexRoute: typeof AuthedDashboardAccountIndexRoute
}

const AuthedDashboardAccountRouteRouteChildren: AuthedDashboardAccountRouteRouteChildren =
  {
    AuthedDashboardAccountIndexRoute: AuthedDashboardAccountIndexRoute,
  }

const AuthedDashboardAccountRouteRouteWithChildren =
  AuthedDashboardAccountRouteRoute._addFileChildren(
    AuthedDashboardAccountRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardProfileSlugRouteRoute: typeof AuthedDashboardProfileSlugRouteRouteWithChildren
  AuthedDashboardAccountRouteRoute: typeof AuthedDashboardAccountRouteRouteWithChildren
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardProfileSlugRouteRoute:
    AuthedDashboardProfileSlugRouteRouteWithChildren,
  AuthedDashboardAccountRouteRoute:
    AuthedDashboardAccountRouteRouteWithChildren,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface MarketingRouteChildren {
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingContactRoute: MarketingContactRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PublicRouteChildren {
  PublicProfileSlugListSlugRoute: typeof PublicProfileSlugListSlugRoute
  PublicProfileSlugIndexRoute: typeof PublicProfileSlugIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicProfileSlugListSlugRoute: PublicProfileSlugListSlugRoute,
  PublicProfileSlugIndexRoute: PublicProfileSlugIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/contact': typeof MarketingContactRoute
  '/auth/auth-confirm': typeof AuthAuthConfirmRoute
  '/auth/auth-error': typeof AuthAuthErrorRoute
  '/auth/auth-verify': typeof AuthAuthVerifyRoute
  '/': typeof MarketingIndexRoute
  '/dashboard/$profileSlug': typeof AuthedDashboardProfileSlugRouteRouteWithChildren
  '/dashboard/account': typeof AuthedDashboardAccountRouteRouteWithChildren
  '/$profileSlug/$listSlug': typeof PublicProfileSlugListSlugRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/$profileSlug': typeof PublicProfileSlugIndexRoute
  '/dashboard/$profileSlug/$listSlug': typeof AuthedDashboardProfileSlugListSlugRoute
  '/dashboard/$profileSlug/': typeof AuthedDashboardProfileSlugIndexRoute
  '/dashboard/account/': typeof AuthedDashboardAccountIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/contact': typeof MarketingContactRoute
  '/auth/auth-confirm': typeof AuthAuthConfirmRoute
  '/auth/auth-error': typeof AuthAuthErrorRoute
  '/auth/auth-verify': typeof AuthAuthVerifyRoute
  '/': typeof MarketingIndexRoute
  '/$profileSlug/$listSlug': typeof PublicProfileSlugListSlugRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/$profileSlug': typeof PublicProfileSlugIndexRoute
  '/dashboard/$profileSlug/$listSlug': typeof AuthedDashboardProfileSlugListSlugRoute
  '/dashboard/$profileSlug': typeof AuthedDashboardProfileSlugIndexRoute
  '/dashboard/account': typeof AuthedDashboardAccountIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/auth/auth-confirm': typeof AuthAuthConfirmRoute
  '/auth/auth-error': typeof AuthAuthErrorRoute
  '/auth/auth-verify': typeof AuthAuthVerifyRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authed/dashboard/$profileSlug': typeof AuthedDashboardProfileSlugRouteRouteWithChildren
  '/_authed/dashboard/account': typeof AuthedDashboardAccountRouteRouteWithChildren
  '/_public/$profileSlug/$listSlug': typeof PublicProfileSlugListSlugRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_public/$profileSlug/': typeof PublicProfileSlugIndexRoute
  '/_authed/dashboard/$profileSlug/$listSlug': typeof AuthedDashboardProfileSlugListSlugRoute
  '/_authed/dashboard/$profileSlug/': typeof AuthedDashboardProfileSlugIndexRoute
  '/_authed/dashboard/account/': typeof AuthedDashboardAccountIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | ''
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/contact'
    | '/auth/auth-confirm'
    | '/auth/auth-error'
    | '/auth/auth-verify'
    | '/'
    | '/dashboard/$profileSlug'
    | '/dashboard/account'
    | '/$profileSlug/$listSlug'
    | '/dashboard'
    | '/$profileSlug'
    | '/dashboard/$profileSlug/$listSlug'
    | '/dashboard/$profileSlug/'
    | '/dashboard/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | ''
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/contact'
    | '/auth/auth-confirm'
    | '/auth/auth-error'
    | '/auth/auth-verify'
    | '/'
    | '/$profileSlug/$listSlug'
    | '/dashboard'
    | '/$profileSlug'
    | '/dashboard/$profileSlug/$listSlug'
    | '/dashboard/$profileSlug'
    | '/dashboard/account'
  id:
    | '__root__'
    | '/auth'
    | '/_authed'
    | '/_marketing'
    | '/_public'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_marketing/contact'
    | '/auth/auth-confirm'
    | '/auth/auth-error'
    | '/auth/auth-verify'
    | '/_marketing/'
    | '/_authed/dashboard/$profileSlug'
    | '/_authed/dashboard/account'
    | '/_public/$profileSlug/$listSlug'
    | '/_authed/dashboard/'
    | '/_public/$profileSlug/'
    | '/_authed/dashboard/$profileSlug/$listSlug'
    | '/_authed/dashboard/$profileSlug/'
    | '/_authed/dashboard/account/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth",
        "/_authed",
        "/_marketing",
        "/_public",
        "/login",
        "/onboarding",
        "/signup"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/auth-confirm",
        "/auth/auth-error",
        "/auth/auth-verify"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard/$profileSlug",
        "/_authed/dashboard/account",
        "/_authed/dashboard/"
      ]
    },
    "/_marketing": {
      "filePath": "_marketing.tsx",
      "children": [
        "/_marketing/contact",
        "/_marketing/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/$profileSlug/$listSlug",
        "/_public/$profileSlug/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_marketing/contact": {
      "filePath": "_marketing.contact.tsx",
      "parent": "/_marketing"
    },
    "/auth/auth-confirm": {
      "filePath": "auth/auth-confirm.tsx",
      "parent": "/auth"
    },
    "/auth/auth-error": {
      "filePath": "auth/auth-error.tsx",
      "parent": "/auth"
    },
    "/auth/auth-verify": {
      "filePath": "auth/auth-verify.tsx",
      "parent": "/auth"
    },
    "/_marketing/": {
      "filePath": "_marketing.index.tsx",
      "parent": "/_marketing"
    },
    "/_authed/dashboard/$profileSlug": {
      "filePath": "_authed/dashboard/$profileSlug/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/$profileSlug/$listSlug",
        "/_authed/dashboard/$profileSlug/"
      ]
    },
    "/_authed/dashboard/account": {
      "filePath": "_authed/dashboard/account/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/account/"
      ]
    },
    "/_public/$profileSlug/$listSlug": {
      "filePath": "_public/$profileSlug/$listSlug.tsx",
      "parent": "/_public"
    },
    "/_authed/dashboard/": {
      "filePath": "_authed/dashboard/index.tsx",
      "parent": "/_authed"
    },
    "/_public/$profileSlug/": {
      "filePath": "_public/$profileSlug/index.tsx",
      "parent": "/_public"
    },
    "/_authed/dashboard/$profileSlug/$listSlug": {
      "filePath": "_authed/dashboard/$profileSlug/$listSlug.tsx",
      "parent": "/_authed/dashboard/$profileSlug"
    },
    "/_authed/dashboard/$profileSlug/": {
      "filePath": "_authed/dashboard/$profileSlug/index.tsx",
      "parent": "/_authed/dashboard/$profileSlug"
    },
    "/_authed/dashboard/account/": {
      "filePath": "_authed/dashboard/account/index.tsx",
      "parent": "/_authed/dashboard/account"
    }
  }
}
ROUTE_MANIFEST_END */
