/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as AuthConfirmImport } from './routes/auth-confirm'
import { Route as MarketingImport } from './routes/_marketing'
import { Route as AuthedImport } from './routes/_authed'
import { Route as MarketingIndexImport } from './routes/_marketing.index'
import { Route as MarketingContactImport } from './routes/_marketing.contact'
import { Route as AuthedOnboardingImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexImport } from './routes/_authed/dashboard/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthConfirmRoute = AuthConfirmImport.update({
  id: '/auth-confirm',
  path: '/auth-confirm',
  getParentRoute: () => rootRoute,
} as any)

const MarketingRoute = MarketingImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const MarketingIndexRoute = MarketingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)

const MarketingContactRoute = MarketingContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)

const AuthedOnboardingRoute = AuthedOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRouteRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingImport
      parentRoute: typeof rootRoute
    }
    '/auth-confirm': {
      id: '/auth-confirm'
      path: '/auth-confirm'
      fullPath: '/auth-confirm'
      preLoaderRoute: typeof AuthConfirmImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingImport
      parentRoute: typeof AuthedImport
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactImport
      parentRoute: typeof MarketingImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexImport
      parentRoute: typeof MarketingImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexImport
      parentRoute: typeof AuthedDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface MarketingRouteChildren {
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingContactRoute: MarketingContactRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MarketingRouteWithChildren
  '/auth-confirm': typeof AuthConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/contact': typeof MarketingContactRoute
  '/': typeof MarketingIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthedRouteWithChildren
  '/auth-confirm': typeof AuthConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/contact': typeof MarketingContactRoute
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/auth-confirm': typeof AuthConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth-confirm'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/onboarding'
    | '/contact'
    | '/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth-confirm'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/contact'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authed'
    | '/_marketing'
    | '/auth-confirm'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/_marketing/contact'
    | '/_marketing/'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/_marketing",
        "/auth-confirm",
        "/login",
        "/signup"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard",
        "/_authed/onboarding"
      ]
    },
    "/_marketing": {
      "filePath": "_marketing.tsx",
      "children": [
        "/_marketing/contact",
        "/_marketing/"
      ]
    },
    "/auth-confirm": {
      "filePath": "auth-confirm.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/"
      ]
    },
    "/_authed/onboarding": {
      "filePath": "_authed/onboarding.tsx",
      "parent": "/_authed"
    },
    "/_marketing/contact": {
      "filePath": "_marketing.contact.tsx",
      "parent": "/_marketing"
    },
    "/_marketing/": {
      "filePath": "_marketing.index.tsx",
      "parent": "/_marketing"
    },
    "/_authed/dashboard/": {
      "filePath": "_authed/dashboard/index.tsx",
      "parent": "/_authed/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
